image: docker:stable

stages:
  - build
  - test
  - deploy


# variables:
#   IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_TAG: 'gcr.io/<PROJECT_ID>/node-kubernetes:v0.0.1'
    PROJECT_ID: local-tempo-266715
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_TAG || true
    - docker build
        --cache-from $DOCKER_IMAGE_TAG
        --tag $DOCKER_IMAGE_TAG
        --file ./Dockerfile
          "."
    - docker push ${DOCKER_IMAGE_TAG}

test:
  stage: test
  image: 
    name: ${DOCKER_IMAGE_TAG}
    entrypoint: [""]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - npm install
  script:
    - pm2 start server.js
    - npm test
 
deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DEPLOYMENT_ENVIRONMENT: GKE PROD
    CLUSTER_NAME: nodeapp
    CLOUDSDK_COMPUTE_ZONE: europe-west2
    DOCKER_IMAGE_TAG: 'gcr.io/<PROJECT_ID>/node-kubernetes:v0.0.1'
  script:
    - ./release.sh

