image: docker:stable

stages:
  - build
  - test
  

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:latest || true
    - docker build
        --cache-from $IMAGE:latest
        --tag $IMAGE:latest
        --file ./Dockerfile
        "."
    - docker push $IMAGE:latest

test:
  stage: test
  image: 
    name: $IMAGE:latest
    entrypoint: ["/bin/sh"]
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - nohup node server.js &
  after_script:
    - npm run test
    # - kill -9 $(ps aux | grep '\snode\s' | awk '{print $2}')
    
 

